version: '3'

services:
  db:
    image: mariadb:latest
    volumes:
      - ./docker/db_data:/var/lib/mysql
    restart: always
    container_name: db
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: wordpress
      MARIADB_USER: user
      MARIADB_PASSWORD: password

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('FORCE_SSL_ADMIN', true);
        define('WP_HOME','https://local.env.com');
        define('WP_SITEURL','https://local.env.com');
    volumes:
      - wordpress:/var/www/html
    ports:
      - 8080:80

  webserver:
    depends_on:
      - wordpress
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - wordpress:/var/www/html
      - ./docker/certs:/etc/nginx/certs
      - ./docker/nginx:/etc/nginx/conf.d

volumes:
  wordpress:
  dbdata:
